name: Build Resume PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build PDF
        uses: xu-cheng/texlive-action@v2
        with:
          root_file: resume.tex
          pre_compile: |
            tlmgr install fontawesome5
          compiler: xelatex
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf
          
      - name: Deploy to repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit PDF to main branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          # Ensure we're in the root directory
          cd $GITHUB_WORKSPACE
          # Configure git
          git config --global push.autoSetupRemote true
          # Add the new PDF
          git add resume.pdf
          git commit -m "Update resume PDF" || echo "No changes to commit"
          git push origin main 